[project]
name = 'clardentity'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.clardentity]
path = 'contracts/clardentity.clar'
clarity_version = 4
epoch = "3.3"
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
